-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQRDe6K1iGF2IktyG
EGOfytm+sbPuKCbsAKsnrsx4rGugCgYIKoZIzj0DAQehRANCAATNT1iAkt6pkXzI
e7A0kgiF7R+ItFZkg5IpoqI+kDFYYOAob8ASWoPqwugla3MCH9q2/9NO1wZdrgOB
AdazDz4Z
-----END PRIVATE KEY-----